### ISSUE TITLE
Add application to pypi

### ISSUE THREAD

**Issue by signebedi** [signebedi/libreforms-fastapi#113]
> Here we need to make sure that the application works as expected when we pip install it. My worry is that a few things will break, as all our testing has been done with a locally installed git repo...

_Originally posted by @signebedi in https://github.com/signebedi/libreforms-fastapi/issues/13#issuecomment-2026582727_

**Comment by signebedi** [comment]
[bug] pypi package cannot find static or template directories
```
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sig/some_repo/venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/home/sig/some_repo/venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/sig/some_repo/venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/sig/some_repo/venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/sig/some_repo/venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/sig/some_repo/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sig/some_repo/venv/lib/python3.10/site-packages/libreforms_fastapi/app/__init__.py", line 347, in <module>
    app.mount("/static", StaticFiles(directory="libreforms_fastapi/app/static"), name="static")
  File "/home/sig/some_repo/venv/lib/python3.10/site-packages/starlette/staticfiles.py", line 59, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'libreforms_fastapi/app/static' does not exist
```
This likely stems from https://github.com/signebedi/libreforms-fastapi/blob/cf8dca292da3abe4a13ddef7a7946cef85c5d53b/libreforms_fastapi/app/__init__.py#L347
