### ISSUE TITLE
[bug] AttributeError: module 'pandas' has no attribute 'DataFrame'

### ISSUE THREAD

**Issue by janoskabedis** [signebedi/libreforms-fastapi#223]
```
Traceback (most recent call last):
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/middleware/authentication.py", line 49, in __call__
    await self.app(scope, receive, send)
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/libreforms-fastapi/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/libreforms-fastapi/libreforms_fastapi/app/__init__.py", line 876, in api_form_export_excel
    document_path = doc_db.get_all_documents_as_excel(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/libreforms-fastapi/libreforms_fastapi/utils/document_database.py", line 825, in get_all_documents_as_excel
    df = pd.DataFrame(documents)
         ^^^^^^^^^^^^
AttributeError: module 'pandas' has no attribute 'DataFrame'
```

**Comment by janoskabedis** [comment]
No issue importing pandas and instantiating dataframes outside the application scope...
![image](https://github.com/signebedi/libreforms-fastapi/assets/64809971/5be88841-2f42-4c23-b546-f6d83ea88774)

**Comment by signebedi** [comment]
Try `chown -R fastapi:fastapi /opt/libreforms_fastapi`.
